### ISSUE TITLE
how to download the dataset

### ISSUE THREAD

**Issue by xuxumiao777** [MegaScenes/dataset#1]
Nice work! but the readme is too tricky. When I use wget http:*** , I can just download a index.html. Could you please tell me a simple way to download your dataset? Thank you.

**Comment by jianglh-WHU** [comment]
I also wanna know how to download the dataset by base URL.

**Comment by j0seo** [comment]
I successfully downloaded the dataset using the command `aws s3 sync --no-sign-request s3://megascenes/ ./` after installing AWS CLI.

**Comment by jot-jt** [comment]
Thanks for the feedback, we will update the documentation with download instructions. I recommend downloading the dataset using the AWS CLI command as j0seo mentioned.

wget can only download singular files, while the AWS CLI can recursively download all files in a directory. 

To download a file with wget, an example is `wget https://megascenes.s3.us-west-2.amazonaws.com/databases/descriptors/000/000/descriptors.db.gz`. But multiple commands need to be run to download the entire `descriptors` folder.

**Comment by jianglh-WHU** [comment]
> I successfully downloaded the dataset using the command `aws s3 sync --no-sign-request s3://megascenes/ ./` after installing AWS CLI.

It works!
