### ISSUE TITLE
Images Licenses 

### ISSUE THREAD

**Issue by felipecadar** [MegaScenes/dataset#2]
Hi there! Congrats for the amazing work!

About this comment:

> License
> This dataset is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). The photos in the images/ folder have their own licenses.

I know it might be a lot of work, but I think the community would appreciate a clear index showing which images are under permissive licenses. 

By any chance, does anyone already have this index?

**Comment by jot-jt** [comment]
Hi, thank you for the suggestion! We aggregated image metadata into a table and documented it here: https://github.com/MegaScenes/dataset/blob/main/README.md#index-of-images

**Comment by felipecadar** [comment]
That's exactly it. 

Thanks and congrats again!

**Comment by VRehnberg** [comment]
Perhaps a link to make it easier to find quickly?

> License
> This dataset is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). The photos in the images/ folder have their own licenses, see [Index of Images](#index-of-images).
